name: instagram_clone
description: Instagram Clone App
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  firebase_core_platform_interface: ^5.0.0
  cached_network_image: ^3.3.0
  uuid: ^3.0.7
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  insta_assets_picker: ^2.2.1
  hashtagable_v3: ^3.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  expandable_page_view: ^1.0.17
  share_plus: ^7.2.2
  flutter_staggered_grid_view: ^0.7.0
  location_picker_flutter_map: ^2.1.0
  animated_text_kit: ^4.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_location_marker: ^8.0.2
  audioplayers: ^5.2.1
  visibility_detector: ^0.4.0+2
  video_editor: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3
  cloudinary: ^1.2.0
  cloudinary_public: ^0.23.1
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: insta
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: poppins1
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: poppins2
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf